service_name: transmission
service_subnet: '10.101.5.0/24'
service_gateway: 10.101.5.1
ip_host_listen: "{{ ip_VPN }}"
br_output: "br-{{ service_name }}"



net_in: [
  '# {{ service_name }}',
  '-A TCP -i {{ dev_BRIDGE_WAN }} -p tcp -m tcp --dport 51413 -m conntrack --ctstate NEW -j ACCEPT',
  '-A UDP -i {{ dev_BRIDGE_WAN }} -p udp -m udp --dport 51413 -m conntrack --ctstate NEW -j ACCEPT'
]
net_out: [
  '# {{ service_name }}',
  '-A OUTPUT -o {{ br_output }} -p tcp -m tcp --dport 9091 -m conntrack --ctstate NEW -j ACCEPT'
]
net_forward: [
  '# {{ service_name }}',
  '## transmission querying internet (hace falta en router?)',
  '#-A FORWARD -i {{ br_output }} -o {{ dev_BRIDGE_WAN }} -p udp -m udp --dport 53 -m conntrack --ctstate NEW -j ACCEPT',
  '#-A FORWARD -i {{ br_output }} -o {{ dev_BRIDGE_WAN }} -p tcp -m tcp --dport 80 -m conntrack --ctstate NEW -j ACCEPT',
  '# transmission listen port',
  '-A FORWARD -i {{ dev_BRIDGE_WAN }} -o {{ br_output }} -p tcp -m tcp --dport 51413 -m conntrack --ctstate NEW -j ACCEPT',
  '-A FORWARD -i {{ dev_BRIDGE_WAN }} -o {{ br_output }} -p udp -m udp --dport 51413 -m conntrack --ctstate NEW -j ACCEPT',
  '# transmission sharing/requesting content?',
  '-A FORWARD -i {{ br_output }} -o {{ dev_BRIDGE_WAN }} -p udp -m udp --sport 51413 -m conntrack --ctstate NEW -j ACCEPT',
  '-A FORWARD -i {{ br_output }} -o {{ dev_BRIDGE_WAN }} -p tcp -m tcp --sport 51413 -m conntrack --ctstate NEW -j ACCEPT',
  '# Vagrant needs network traffic',
  '-A FORWARD -i {{ br_output }} -o {{ br_output }} -j ACCEPT'
]
net_nat: [
  '# {{ service_name }}',
  '# transmission listen port',
  '-A PREROUTING -i {{ dev_BRIDGE_WAN }} -p tcp -m tcp --dport 51413 -j DNAT --to-destination {{ container_ip }}',
  '-A PREROUTING -i {{ dev_BRIDGE_WAN }} -p udp -m udp --dport 51413 -j DNAT --to-destination {{ container_ip }}'
]

# router
services:
  - name: "{{ service_name }}.{{ name_VPN|lower }}.vpn"
    destination: "http://{{ service_name|lower }}:9091"

# nas
#services:
#  - name: "{{ service_name }}.{{ ansible_hostname }}.lan"
#    destination: "{{ service_name }}:9091"
