service_name: monitoring
service_subnet: '10.101.2.0/24'
service_gateway: 10.101.2.1

net_in: [
  '# {{ service_name }}',
  '# prometheus querying host',
  '-A TCP -i br-{{ service_name }} -p tcp -m tcp --dport 9100 -m conntrack --ctstate NEW -j ACCEPT'
]
net_out: [
  '# {{ service_name }}',
  '-A OUTPUT -o br-{{ service_name }} -p tcp -m tcp --dport 80 -m conntrack --ctstate NEW -j ACCEPT'
]

# faltan reglas de dev_BRIDGE_LAN:
net_forward: [
  '# {{ service_name }}',
  '# speedtest querying internet',
  '-A FORWARD -i br-{{ service_name }} -o {{ dev_BRIDGE_WAN }} -p udp -m udp --dport 53 -m conntrack --ctstate NEW  -j ACCEPT',
  '-A FORWARD -i br-{{ service_name }} -o {{ dev_BRIDGE_WAN }} -p tcp -m multiport --dports 80,443,8080 -m conntrack --ctstate NEW  -j ACCEPT',
  '# alermanager sends emails',
  '-A FORWARD -i br-{{ service_name }} -o {{ dev_BRIDGE_WAN }} -p tcp -m tcp --dport 587 -m conntrack --ctstate NEW  -j ACCEPT',
  '# Vagrant needs network traffic',
  '-A FORWARD -i br-{{ service_name }} -o br-{{ service_name }} -j ACCEPT'
]
# estas reglas faltan:
#net_forward:
#  '# querying windows lan hosts',
#  '-A FORWARD -i br-{{ service_name }} -o {{ dev_BRIDGE_LAN }} -p tcp -m tcp --dport 9182 -m conntrack --ctstate NEW -j ACCEPT',
#]

net_nat: []

services:
  - name: "prometheus.{{ name_VPN|lower }}.vpn"
    destination: http://prometheus:9090
  - name: "alertmanager.{{ name_VPN|lower }}.vpn"
    destination: http://alertmanager:9093
  - name: "grafana.{{ name_VPN|lower }}.vpn"
    destination: http://grafana:3000
  - name: "cadvisor.{{ name_VPN|lower }}.vpn"
    destination: http://cadvisor:8080
