---
- name: easy-rsa  |  Copy openssl config
  template:
    src: vars-bionic.j2
    dest: "{{ easy_rsa_dir }}/vars"
    owner: root
    group: root
    mode: 0600 

- name: easy-rsa  |  Clean everything
  command: bash -c ". ./vars && ./clean-all 2> /dev/null"
  args:
    chdir: "{{ easy_rsa_dir }}"
    creates: "{{ easy_rsa_dir }}/keys/ca.crt"


- name: easy-rsa  |  Select openssl.cnf
  file:
    src: "{{ easy_rsa_dir }}/openssl-1.0.0.cnf"
    dest: "{{ easy_rsa_dir }}/openssl.cnf"
    owner: root
    group: root
    state: link

- name: easy-rsa  |  Create CA
  command: bash -c ". ./vars && ./build-ca --batch 2> /dev/null"
  args:
    chdir: "{{ easy_rsa_dir }}"
    creates: "{{ easy_rsa_dir }}/keys/ca.crt"

- name: easy-rsa  |  Create server certificate
  command: bash -c ". ./vars && sh ./build-key-server --batch {{ name_VPN }} 2> /dev/null"
  args:
    chdir: "{{ easy_rsa_dir }}"
    creates: "{{ easy_rsa_dir }}/keys/{{ name_VPN }}.crt"
  notify:
  - Create CRL key

- name: easy-rsa  |  Create Diffie-Hellman key
  command: bash -c ". ./vars && sh ./build-dh 2> /dev/null"
  args:
    chdir: "{{ easy_rsa_dir }}"
    creates: "{{ easy_rsa_dir }}/keys/dh2048.pem"
