---
- block:

  - name: Remove certificates folder
    file:
      path: "{{ easy_rsa_dir }}/pki"
      state: absent


  - name: Re-create certificates folder
    file:
      path: "{{ easy_rsa_dir }}/pki"
      state: directory

  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == 'bionic'



- block:

  - name: Remove certificates folder
    file:
      path: "{{ easy_rsa_dir }}/pki"
      state: absent


  - name: Re-create certificates folder
    file:
      path: "{{ easy_rsa_dir }}/pki"
      state: directory

  when: (ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'focal') or
        (ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'hirsute' or ansible_distribution_release == 'impish') or
        (ansible_distribution == 'Debian')
