---
service_name:   keepalived

#virt_state:     "BACKUP"
#virt_priority:  "100"
virt_state:     "MASTER"
virt_priority:  "101"

net_in: [
  '# {{ service_name }}',
  '# vrrp (112), ah (51)',
  '-A INPUT -i {{ dev_BRIDGE_WAN }} -p vrrp -d 224.0.0.18 -m conntrack --ctstate NEW -j ACCEPT',
  '-A INPUT -i {{ dev_BRIDGE_WAN }} -p ah -d 224.0.0.18 -m conntrack --ctstate NEW -j ACCEPT'
]
net_out: [
  '# {{ service_name }}',
  '# vrrp (112), ah (51)',
  '-A OUTPUT -o {{ dev_BRIDGE_WAN }} -p vrrp -d 224.0.0.18 -m conntrack --ctstate NEW -j ACCEPT',
  '-A OUTPUT -o {{ dev_BRIDGE_WAN }} -p ah -d 224.0.0.18 -m conntrack --ctstate NEW -j ACCEPT'
]
net_forward: []
net_nat: []
