
- name: router  |  Bring bridge interface up Debian
  systemd:
    state: restarted
    name: networking
  
- name: router  |  Bring bridge interface up Ubuntu
  systemd:
    state: restarted
    name: NetworkManager

- name: router  |  Restart dhcp
  service:
    name: isc-dhcp-server
    state: restarted
    daemon_reload: yes

- name: router  |  Restart hostapd
  service:
    name: isc-dhcp-server
    state: restarted
    daemon_reload: yes