---
- name: "{{ proxy_service_name }}  |  Create destiny"
  file:
    path: "{{ item }}"
    state: directory
    mode: '0750'
  with_items:
    - "/opt/{{ proxy_service_name }}"
    - "/opt/{{ proxy_service_name }}/conf.d"
    - "/opt/{{ proxy_service_name }}/fragments"

- name: "{{ proxy_service_name }}  |  Copy docker-compose main fragments"
  template: 
    src: docker_compose/{{ item }}_block.yml.j2
    dest: /opt/{{ proxy_service_name }}/fragments/{{ item }}_block.yml
    owner: root
    group: root
    mode: 0600 
  with_items:
    - 1_head
    - 3_middle
    - 5_end
  register: newdocker

- name: "{{ proxy_service_name }}  |  Copy docker-compose service fragments 1/2"
  template: 
    src: docker_compose/2_network_block.yml.j2
    dest: /opt/{{ proxy_service_name }}/fragments/2_{{ service_name }}.yml
    owner: root
    group: root
    mode: 0600 
  register: newdocker

- name: "{{ proxy_service_name }}  |  Copy docker-compose service fragments 2/2"
  template: 
    src: docker_compose/4_service_block.yml.j2
    dest: /opt/{{ proxy_service_name }}/fragments/4_{{ service_name }}.yml
    owner: root
    group: root
    mode: 0600 
  register: newdocker

- name: "{{ proxy_service_name }}  |  Assemble docker-compose"
  assemble:
    src: /opt/{{ proxy_service_name }}/fragments
    dest: /opt/{{ proxy_service_name }}/docker-compose.yml
    owner: root
    group: root
    mode: 0600 
  register: newdocker

- name: "{{ proxy_service_name }}  |  Copy default config"
  copy: 
    src: default.conf
    dest: /opt/{{ proxy_service_name }}/conf.d/
    owner: root
    group: root
    mode: 0600 
  register: newdocker

- name: "{{ proxy_service_name }}  |  Create virtualhosts"
  template: 
    src: virtualhost.conf.j2
    dest: /opt/{{ proxy_service_name }}/conf.d/{{ service_name }}.conf
    owner: root
    group: root
    mode: 0604
  register: newdocker

- name: "{{ proxy_service_name }}  |  Create a network with pretty name"
  docker_network:
    name: "{{ proxy_service_name }}"
    driver_options:
      com.docker.network.bridge.name: br-{{ proxy_service_name }}
    ipam_config:
      - subnet: "{{ proxy_service_subnet }}"
        gateway: "{{ proxy_service_gateway }}"

- name: "{{ proxy_service_name }}  |  Get container info"
  docker_container_info:
    name: "{{ proxy_service_name }}_{{ proxy_service_name }}_1"
  register: result
  
- name: "{{ proxy_service_name }}  |  Tear down existing services"
  docker_compose:
    project_src: "/opt/{{ proxy_service_name }}"
    #remove_images: yes
    remove_volumes: yes
    state: absent
  when: not result.exists

- name: "{{ proxy_service_name }}  |  Create and start services"
  docker_compose:
    project_src: "/opt/{{ proxy_service_name }}"
  when: newdocker.changed

#- name: "{{ proxy_service_name }}  |  Apply iptables rules"
#  include_role:
#    name: firewall
#
- name: "{{ proxy_service_name }}  |  Copy iptables service fragments"
  template: 
    src: rules.v4
    dest: /root/iptables-fragments/03_{{ proxy_service_name }}
    owner: root
    group: root
    mode: 0600 
  when: "'router' in group_names"
