version: '3.5'

networks:
  {{ service_name }}:
    external:
      name: {{ service_name }}

volumes:
  config:
  cache:

services:
  {{ service_name }}:
    image: jellyfin/jellyfin:latest
    container_name: {{ service_name }}
    expose:
      - 8096
      #- 8920
      - 1900
      -  7359/udp
    restart: always
    volumes:
      - config:/config
      - cache:/cache
      - /docker-share:/docker-share
    #user: uid:gid
    networks:
      - {{ service_name }}
