---
- name: docker  |  Removing previous versions
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
      - docker-ce
      - docker-ce-cli
      - docker-compose
    state: absent
  tags: [ never, uninstall ]



- include: bionic-setup.yml
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_release == 'bionic') or
        (ansible_distribution == 'Debian')

- include: focal-setup.yml
  when: (ansible_distribution == 'Ubuntu') and 
        (ansible_distribution_release == 'focal' or ansible_distribution_release == 'hirsute' or ansible_distribution_release == 'impish' or ansible_distribution_release == 'jammy')



- name: docker  |  Create folder for persistent data
  file:
    path: /docker-share
    state: directory
    owner: www-data
    group: www-data
    mode: 0750

- name: docker  |  Disable autogeneration of iptables rules
  copy:
    src: daemon.json
    dest: /etc/docker/
  notify:
  - Restart docker
#  when: "'router' in group_names"
# en nas tampoco queremos reglas porque se pisan con kvm

- name: docker  |  Ensure docker daemon is running
  systemd:
    state: started
    name: docker
    enabled: yes
