# you can't use this variable here or it will break docker-compose
# if you don't use it, rules defined here will be overwritten later
#service_name: node_exporter
proxy_service_name: proxyhttp
proxy_service_subnet: '10.101.7.0/24'
proxy_service_gateway: 10.101.7.1
ip_host_listen: "{{ ip_VPN }}"
br_output: "br-{{ proxy_service_name }}"

net_in: [
  '# node_exporter',
  '-A TCP -i {{ dev_VPN }} -m tcp -m tcp --dport 80 -m conntrack --ctstate NEW -j ACCEPT'
]
net_out: []
net_forward: []
net_nat: []
