service_name: pihole
service_subnet: '10.101.4.0/24'
service_gateway: 10.101.4.1
ip_host_listen: "{{ ip_VPN }}"
br_output: "br-{{ service_name }}"

pihole_pass: '1234'

net_in: [
  '# {{ service_name }}',
  '# vpn clients querying pihole',
  '-A UDP -i {{ dev_VPN }} -p udp -m udp --dport 53 -m conntrack --ctstate NEW -j ACCEPT',
  '# pihole admin console',
  '-A TCP -i {{ dev_VPN }} -p tcp -m tcp --dport 8080 -m conntrack --ctstate NEW -j ACCEPT'
]
net_out: [
  '# {{ service_name }}',
  '# pihole querying internet',
  '-A OUTPUT -o {{ br_output }} -p udp -m udp --dport 53 -m conntrack --ctstate NEW -j ACCEPT',
  '-A OUTPUT -o {{ br_output }} -p tcp -m multiport --dports 80,443 -m conntrack --ctstate NEW -j ACCEPT'
]
net_forward: [
  '# {{ service_name }}',
  '-A FORWARD -i {{ br_output }} -o {{ dev_WAN }} -j ACCEPT',
  '-A FORWARD -i {{ dev_WAN }} -o {{ br_output }} -j ACCEPT'
]
net_nat: []

# router
services:
  - name: "{{ service_name }}.{{ name_VPN|lower }}.vpn"
    destination: "{{ service_name }}:8888"
