version: '3'

networks:
  {{ service_name }}:
    external:
      name: {{ service_name }}

volumes:
  config:

services:
  {{ service_name }}:
    image: emby/embyserver:latest
    expose:
      - 8096
      - 8920
    restart: unless-stopped
    volumes:
      - config:/config # This is mandatory
      - /docker-share:/docker-share
    environment:
      - UID=33 # The UID to run emby as (default: 2)
      - GID=33 # The GID to run emby as (default 2)
      #- GIDLIST=100 # A comma-separated list of additional GIDs to run emby as (default: 2)
#    devices: # only if hosts has a GPU
#      - "/dev/dri:/dev/dri" # To mount all render nodes for VAAPI/NVDEC/NVENC
    networks:
      - {{ service_name }}
          